### ISSUE TITLE
关于训练得问题

### ISSUE THREAD

**Issue by EillotY** [CommissarMa/MCNN-pytorch#2]
我依据你给出得data_preparation生成得.npy文件（其实里面有一个地方多余，就是你多加了一个break，导致程序直接跳出循环了），开始训练这个train.py，运行有误：报得是gpu out of memory,我采用得是GTX1060 6G 跑得   但是我看了后台其实并没有使用那么多得显存，这是什么原因呢，还是说作者您使用得gpu更大得缘故嘛，这是我以前没有遇到过得一个问题：希望能得到你得回复，感谢

**Comment by CommissarMa** [comment]
mcnn模型的话1060应该也能跑起来的，我当时用的是8g显存的显卡。

**Comment by EillotY** [comment]
好吧 ，1060没有8G显存的 我试试看服务器跑吧
