### ISSUE TITLE
Tried to allocate 18.07 GiB

### ISSUE THREAD

**Issue by anhminh3105** [CommissarMa/MCNN-pytorch#7]
Hi @CommissarMa 

the dropbox link to the Shanghai dataset is broken already and I couldn't make use of the Baidu disk link to download the dataset since I don't have any Chinese account. Could you help fixing this?
Because of that, I tried the model out with the UCF-QNRF_ECCV18 dataset but the training requires allocating 18.07 GiB of memory where my running machine only has 8 GiB. Could you give some advice on how to reduce this amount so that I can train it on my local machine. If possible, could you also open-source the pre-trained models as well?

Thanks in advance.
Minh

**Comment by CommissarMa** [comment]
the mcnn model is relatively small，so out of memory may not happen.&nbsp; you can down sample the input image or cut the image into small patch to solve this problem.&nbsp;



---Original---

**Comment by anhminh3105** [comment]
does resizing the image affect the model performance?

**Comment by CommissarMa** [comment]
yeah，downsample may hurt the performance. and patch may be better.&nbsp;



---Original---

**Comment by anhminh3105** [comment]
> yeah，downsample may hurt the performance. and patch may be better.&nbsp;
> […](#)
> ---Original--- From: "Anh Minh"<notifications@github.com&gt; Date: Tue, Apr 7, 2020 21:35 PM To: "CommissarMa/MCNN-pytorch"<MCNN-pytorch@noreply.github.com&gt;; Cc: "Mention"<mention@noreply.github.com&gt;;"Ma Zhenwei"<960901625@qq.com&gt;; Subject: Re: [CommissarMa/MCNN-pytorch] Tried to allocate 18.07 GiB (#7) does resizing the image affect the model performance? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks a lot for the recommendation. Also, the Shanghaitech dataset link is broken and everywhere else on the internet seemed to also use the same link. could you somehow share that dataset? I would be very appreciated

**Comment by CommissarMa** [comment]
the dataset is in remote server but can not connect because of virus in the whole world and no people can get in the lab.&nbsp; sorry



---Original---

**Comment by anhminh3105** [comment]
Thanks a lot anyway, please hit me up if you reupload it.

Just one more thing I have in mind, since I used your data preparation script to generate density maps for the UCF-QNRF_ECCV18 and its data has a very large resolution, and I also don't know about this for the Shanghaitech dataset as well. In this project, it seemed you didn't generate image patches so I wonder if you used patched images in your training at all? if yes, could you share the code? it would make my life a bit easier and make learning faster :p

**Comment by CommissarMa** [comment]
shanghaitech will not happen&nbsp; out of memory.&nbsp; when I get access to the server I will give you the dataset at once.&nbsp;



---Original---

**Comment by anhminh3105** [comment]
@CommissarMa Thanks very much ☺️
